#!/usr/bin/env bash

export SNGGEMINIBIN="/home/richard/pipeline/gemini/tools/bin"
#GEMINIBIN="/home/richard/pipeline/gemini/data/anaconda/bin"
export SNGSCRIPTS="/home/richard/pipeline/SeqNextGen_pipeline/Phenoparser/scripts"
export SNGBCFTOOLS="/usr/local/src/bcftools-1.6/"
export SNGHTSLIB="/usr/local/src/htslib-1.6/"
export SNGGRABIX="/usr/local/src/grabix/grabix-master/"
export SNGDOCKERCMD="sudo docker"
export SNGGEMINI_TMP="geminitmp"
export SNGPLBIN="/usr/local/src/Phenolyzer/phenolyzer"
export SNGPPBIN="/home/richard/pipeline/SeqNextGen_pipeline/Phenoparser/src"

export PATH=$PATH:$SNGGEMINIBIN:$SNGSCRIPTS:$SNGBCFTOOLS:$SNGHTSLIB:$SNGGRABIX:$SNGPLBIN:$SNGPPBIN
